from flask import Flask, render_template, request, jsonify
import subprocess
import os
import uuid
from pathlib import Path

app = Flask(__name__)

# Calculate absolute paths
FRONTEND_DIR = Path(__file__).parent.absolute()
PROJECT_ROOT = FRONTEND_DIR.parent
BACKEND_BUILD_DIR = PROJECT_ROOT / 'backend_c' / 'build'
DISASTER_ALLOC_EXE = BACKEND_BUILD_DIR / 'disaster_alloc.exe'

@app.route('/')
def index():
    """Serve the main dashboard page"""
    return render_template('index.html')

@app.route('/allocate', methods=['POST'])
def allocate():
    """
    Handle allocation requests from the frontend
    Expected JSON body: {'data': 'user input from textarea'}
    """
    temp_input_file = None
    report_file = None
    
    try:
        data = request.get_json()
        
        if not data or 'data' not in data:
            return jsonify({
                'status': 'error',
                'message': 'No data provided'
            }), 400
        
        user_input = data.get('data', '').strip()
        
        if not user_input:
            return jsonify({
                'status': 'error',
                'message': 'Input data is empty'
            }), 400
        
        # Create temporary input file with unique name in frontend directory
        temp_filename = f'temp_input_{uuid.uuid4().hex}.txt'
        temp_input_file = FRONTEND_DIR / temp_filename
        
        with open(temp_input_file, 'w') as f:
            f.write(user_input)
        
        # Calculate relative path from backend_c/build/ to the temp file
        # This will be something like: ../../frontend_python/temp_input_XXX.txt
        relative_input_path = os.path.relpath(temp_input_file, BACKEND_BUILD_DIR)
        
        # Run the C executable from backend_c/build/ directory
        try:
            result = subprocess.run(
                [str(DISASTER_ALLOC_EXE), relative_input_path],
                cwd=str(BACKEND_BUILD_DIR),
                capture_output=True,
                text=True,
                timeout=30
            )
            
            # Check for errors
            if result.returncode != 0:
                return jsonify({
                    'status': 'error',
                    'message': f'Backend process failed with return code {result.returncode}',
                    'stderr': result.stderr,
                    'stdout': result.stdout
                }), 500
            
            # Read the report file generated by C program in backend_c/build/
            report_file = BACKEND_BUILD_DIR / 'report.txt'
            
            if not report_file.exists():
                return jsonify({
                    'status': 'error',
                    'message': 'Report file not generated by backend',
                    'stdout': result.stdout,
                    'stderr': result.stderr
                }), 500
            
            with open(report_file, 'r') as f:
                report_content = f.read()
            
            return jsonify({
                'status': 'success',
                'report': report_content
            })
                
        except subprocess.TimeoutExpired:
            return jsonify({
                'status': 'error',
                'message': 'Backend process timed out after 30 seconds'
            }), 500
        except FileNotFoundError:
            return jsonify({
                'status': 'error',
                'message': f'Executable not found at: {DISASTER_ALLOC_EXE}'
            }), 500
    
    except Exception as e:
        return jsonify({
            'status': 'error',
            'message': f'Unexpected error: {str(e)}'
        }), 500
    
    finally:
        # Cleanup: Delete temporary files
        if temp_input_file and temp_input_file.exists():
            try:
                os.remove(temp_input_file)
            except Exception:
                pass
        
        if report_file and report_file.exists():
            try:
                os.remove(report_file)
            except Exception:
                pass

@app.route('/run_with_input', methods=['POST'])
def run_with_input():
    """
    Alternative endpoint for structured input (for dashboard UI)
    Expected JSON body:
    {
        "regions": [1, 4, 7],
        "severities": [5, 8, 3],
        "manualResourceEntry": false,
        "manualStock": {}
    }
    """
    temp_input_file = None
    report_file = None
    
    try:
        data = request.get_json()
        
        if not data:
            return jsonify({
                'status': 'error',
                'message': 'No data provided'
            }), 400
        
        regions = data.get('regions', [])
        severities = data.get('severities', [])
        
        if not regions or not severities:
            return jsonify({
                'status': 'error',
                'message': 'Regions and severities are required'
            }), 400
        
        if len(regions) != len(severities):
            return jsonify({
                'status': 'error',
                'message': 'Regions and severities must have the same length'
            }), 400
        
        # Create temporary input file with unique name
        temp_filename = f'temp_input_{uuid.uuid4().hex}.txt'
        temp_input_file = FRONTEND_DIR / temp_filename
        
        with open(temp_input_file, 'w') as f:
            f.write(f"{len(regions)}\n")
            for region_id, severity in zip(regions, severities):
                f.write(f"{region_id} {severity}\n")
        
        # Calculate relative path from backend_c/build/ to the temp file
        relative_input_path = os.path.relpath(temp_input_file, BACKEND_BUILD_DIR)
        
        # Run the C executable from backend_c/build/ directory
        try:
            result = subprocess.run(
                [str(DISASTER_ALLOC_EXE), relative_input_path],
                cwd=str(BACKEND_BUILD_DIR),
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if result.returncode != 0:
                return jsonify({
                    'status': 'error',
                    'message': f'Backend process failed with return code {result.returncode}',
                    'stderr': result.stderr,
                    'stdout': result.stdout
                }), 500
            
            # Read the report file
            report_file = BACKEND_BUILD_DIR / 'report.txt'
            
            if not report_file.exists():
                return jsonify({
                    'status': 'error',
                    'message': 'Report file not generated',
                    'stdout': result.stdout,
                    'stderr': result.stderr
                }), 500
            
            with open(report_file, 'r') as f:
                report_content = f.read()
            
            return jsonify({
                'status': 'success',
                'report': report_content
            })
                
        except subprocess.TimeoutExpired:
            return jsonify({
                'status': 'error',
                'message': 'Backend process timed out'
            }), 500
        except FileNotFoundError:
            return jsonify({
                'status': 'error',
                'message': f'Executable not found at: {DISASTER_ALLOC_EXE}'
            }), 500
    
    except Exception as e:
        return jsonify({
            'status': 'error',
            'message': str(e)
        }), 500
    
    finally:
        # Cleanup
        if temp_input_file and temp_input_file.exists():
            try:
                os.remove(temp_input_file)
            except Exception:
                pass
        
        if report_file and report_file.exists():
            try:
                os.remove(report_file)
            except Exception:
                pass

if __name__ == '__main__':
    # Verify paths on startup
    print(f"Frontend Directory: {FRONTEND_DIR}")
    print(f"Backend Build Directory: {BACKEND_BUILD_DIR}")
    print(f"Executable Path: {DISASTER_ALLOC_EXE}")
    print(f"Executable exists: {DISASTER_ALLOC_EXE.exists()}")
    
    app.run(debug=True, port=5000)